/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "options": "选项",
    "notice": "注意",
    "help": "帮助",
    "save": "保存",
    "reset": "重置",
    "- SHARK GAME -": "- 鲨鱼之心 -",
    "Stuff": "东西",
    "You are a shark in a strange blue sea.": "你是陌生蓝色大海中的一条鲨鱼。",
    "You can permanently disable this mode in the options menu.": "您可以在选项菜单中永久禁用此模式。",
    "You feel a bit hungry.": "你觉得有点饿。",
    "You seem to have gone inactive for more than 2 minutes!": "您似乎已超过 2 分钟不活动！",
    "Catch fish": "捕鱼",
    "changelog": "更新日志",
    "click to dismiss.": "点击关闭。",
    "credits": "鸣谢",
    "discord": "discord",
    "donate": "捐赠",
    "IDLE MODE": "放置模式",
    "Loaded game.": "游戏已加载。",
    "Log": "日志",
    "- Sharkpocalypse -": "- 鲨鱼启示录 -",
    "animals": "动物",
    "Ate a monkfish.": "吃了一条安康鱼。",
    "Ate a shark. Wait. No, it wasn't a shark.": "吃了一条鲨鱼。 等等。 不，那不是鲨鱼。",
    "Ate a swedish fish.": "吃了一条瑞典鱼。",
    "fish": "鱼",
    "Now autosaving every 5 minutes.": "现在每 5 分钟自动保存一次。",
    "Offline time is being stored in a button above the resource\n                        table.": "离线时间存储在资源表上方的按钮中。\n",
    "Recruit shark": "招募鲨鱼",
    "You attract the attention of a shark. Maybe they can help you catch fish!": "你吸引了一条鲨鱼的注意。 也许它们可以帮你抓鱼！",
    "- Strange Oceans -": "- 奇异的海洋 -",
    "Ate a kipper. Wait. Hang on.": "吃了一个腌鱼。 等待。 不挂断。",
    "Ate a marlin.": "吃了一条马林鱼。",
    "Ate a perch.": "吃了一条鲈鱼。",
    "Ate a pollock.": "吃了一条鳕鱼。",
    "Ate a salmon.": "吃了一条鲑鱼。",
    "Ate a swordfish.": "吃了一条剑鱼。",
    "Ate a trout.": "吃了一条鳟鱼。",
    "Ate a tuna.": "吃了一条金枪鱼。",
    "Ate a whitefish.": "吃了一条白鱼。",
    "Ate an anchovy.": "吃了一条凤尾鱼。",
    "Dropped the bass.": "放弃了贝斯。",
    "frenzy": "疯狂",
    "a": "一条",
    "PRODUCES": "生产",
    "Recruit a shark to help catch more fish.": "招募鲨鱼来帮助捕获更多的鱼。",
    "shark": "鲨鱼",
    "Use your natural shark prowess to find and catch a fish.": "使用您天生的鲨鱼能力来寻找和捕鱼。",
    "A atlantic torpedo ray joins you.": "大西洋鱼雷鳐加入你。",
    "A blacktip reef shark joins you.": "一条黑鳍礁鲨加入您的行列。",
    "A giant shovelnose ray joins you.": "一条巨大的铲鼻鳐加入你。",
    "A nervous shark joins you.": "一条神经过敏的鲨鱼加入你的行列。",
    "A pacific cownose ray joins you.": "一条太平洋牛鼻鳐加入您的行列。",
    "A silky shark joins you.": "一条柔滑的鲨鱼加入你的行列。",
    "A spotted stingaree joins you.": "一条斑黄貂鱼加入您的行列。",
    "A tiger shark joins you.": "一条虎鲨加入了你。",
    "at": "在",
    "Flesh of the ocean floor.": "海底的肉。",
    "Hire a ray to help collect fish. They might kick up some sand from the seabed.": "雇用鳐鱼来帮助收集鱼。 他们可能会从海底踢出一些沙子。",
    "Hire ray": "雇用鳐鱼",
    "rays": "鳐鱼",
    "ray": "鳐鱼",
    "sand": "沙子",
    "sharks": "鲨鱼",
    "Some rays drift over.": "一些鳐鱼游过。",
    "stuff": "东西",
    "TOGGLE": "切换",
    "IS PRODUCED BY": "正在生产",
    "SPEED": "速度",
    "The hunted.": "猎物。",
    "ARE PRODUCED BY": "生产于",
    "- Weird Oceans -": "- 奇异的海洋 -",
    "A crab starts sifting shiny things out of the sand.": "一只螃蟹开始从沙子里筛出闪亮的东西。",
    "A crocodile shark joins you.": "鳄鱼鲨加入了你。",
    "A dogfish joins you.": "一条狗鱼加入你。",
    "A dusky whaler shark joins you.": "一条昏暗的捕鲸鲨加入你的行列。",
    "A graceful shark joins you.": "一条优雅的鲨鱼加入您的行列。",
    "A hammerhead shark joins you.": "一条双髻鲨加入你的行列。",
    "A lemon shark joins you.": "柠檬鲨会加入你。",
    "A mako shark joins you.": "一只灰鲭鲨加入你的行列。",
    "A pigeye shark joins you.": "一只猪眼鲨加入你的行列。",
    "A puget sound king crab joins you.": "一只普吉特海湾帝王蟹加入您的行列。",
    "A purple shore crab joins you.": "一只紫色的岸蟹加入您的行列。",
    "A round stingray joins you.": "一条圆形的黄貂鱼会加入您的行列。",
    "A sliteye shark joins you.": "一条缝眼鲨加入您的行列。",
    "A spot-tail shark joins you.": "一条斑尾鲨加入您的行列。",
    "A white shark joins you.": "一条白鲨加入你。",
    "Acquire crab": "获得螃蟹",
    "An oceanic whitetip shark joins you.": "一条海洋白鳍鲨加入您的行列。",
    "Ate a bass.": "吃了一条鲈鱼。",
    "buy custom": "自定义购买",
    "buy max": "购买最大",
    "crab": "螃蟹",
    "crabs": "螃蟹",
    "- Maws -": "- 花胶 -",
    "All": "全部",
    "Basic": "基础",
    "- Lobster's Paradise -": "- 龙虾的天堂 -",
    "- NOT FINISHED -": "- 未完成 -",
    "ARE PRODUCING": "正在生产",
    "buy 1/2 max amount of things": "购买最多 1/2 的东西",
    "buy 1/3 max amount of things": "购买最多 1/3 的东西",
    "buy custom amount of things": "购买自定义数量的东西",
    "buy max amount of things": "购买最大数量的东西",
    "crystals": "水晶",
    "Dutiful, loyal crustaceans.": "尽职尽责、忠诚的甲壳类动物。",
    "Frenzy": "疯狂",
    "Jobs": "工作",
    "Kindred to the sharks.": "与鲨鱼有血缘关系。",
    "The crystals are shiny. Some sharks stare at them curiously.": "水晶闪闪发亮，一些鲨鱼好奇地盯着它们。",
    "Train science shark": "训练科学家鲨鱼",
    "- Sharkware Edition -": "- 鲨软版 -",
    "- doo doo do-do do-do -": "- 嘟嘟嘟嘟嘟嘟 -",
    "A banded stingaree joins you.": "一条带状黄貂鱼加入你。",
    "A bignose shark joins you.": "一条大鼻鲨加入你。",
    "A bluespotted maskray joins you.": "一条 蓝色斑点的面具鱼 将加入您的行列。",
    "A bulls-eye electric ray joins you.": "一条靶心电鳐加入你。",
    "A butterfly crab joins you.": "一只蝴蝶蟹加入你的行列。",
    "A clownnose ray joins you.": "一条小丑鱼会加入你。",
    "A dungeness crab joins you.": "一只珍宝蟹加入您的行列。",
    "A eastern fiddler ray joins you.": "东方提琴手鳐加入你。",
    "A flattop crab joins you.": "一只平顶蟹加入您的行列。",
    "A golf-ball crab joins you.": "一只高尔夫球蟹加入您的行列。",
    "A graceful decorator crab joins you.": "优雅的装饰蟹加入您的行列。",
    "A graceful kelp crab joins you.": "优雅的海带蟹加入您的行列。",
    "A greenmark hermit joins you.": "一位绿标隐士加入您的行列。",
    "A hardnose shark joins you.": "一只硬鼻鲨会加入你的行列。",
    "A heart crab joins you.": "一只心蟹加入你的行列。",
    "A longhorn decorator crab joins you.": "一只长角装饰蟹加入您的行列。",
    "A milk shark joins you.": "一条奶鲨加入你的行列。",
    "A moss crab joins you.": "一只青苔蟹加入你的行列。",
    "A northern kelp crab joins you.": "一只北方海带蟹加入您的行列。",
    "A ocellated torpedo joins you.": "一个单眼鱼雷加入你。",
    "A oman masked ray joins you.": "一条阿曼蒙面鳐加入您的行列。",
    "A panther torpedo ray joins you.": "黑豹鱼雷射线加入你。",
    "A red rock crab joins you.": "一只红色的岩蟹加入您的行列。",
    "A scaled crab joins you.": "一只有鳞的螃蟹加入你的行列。",
    "A shorttailed electric ray joins you.": "一条短尾电射线加入你。",
    "A sparesly-spotted stingaree joins you.": "一只零星的黄貂鱼会加入你的行列。",
    "A speartooth shark joins you.": "一条长矛鲨加入你。",
    "A spotted torpedo ray joins you.": "一条有斑点的鱼雷射线加入您的行列。",
    "A widehand hermit joins you.": "一位宽手隐士加入您的行列。",
    "Ate a carp.": "吃了一条鲤鱼。",
    "Ate a cod.": "吃了一条鳕鱼。",
    "Ate a flounder.": "吃了一个比目鱼。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    "The above variably-named Shark Game": "上The above variably-named Shark Game",
    "Cirrial": "Cirrial",
    'x': 'x',
    'All rights reserved.': 'All rights reserved.',
    "spencers145": "spencers145",
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "(you have ": "（你有 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)\)$/,
    /^\t([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^\t([\d\.]+)K$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^buy (.+) max$/, '购买最大值的 $1'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^buy ([\d\.]+)$/, '购买 $1'],
    [/^buy ([\d\.]+) amount of things$/, '购买 $1 次'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+)$/, '成本：$1'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);